#url: https://yplug.github.io
#baseurl:

# Site settings
title: Plug And Trade
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Patrick Redestam
  pic: 1
  position: CEO/Barista
  social:
    - title: linkedin
      url: https://se.linkedin.com/in/patrick-redestam-196318
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Henrik Jönsson
  pic: 2
  position: Señor Developer
  social:
    #- title: twitter
    #  url: #
    - title: github
      url: https://github.com/henkish
    - title: linkedin
      url: https://se.linkedin.com/in/henkish

- name: Christine Redestam
  pic: 7
  position: CFO/CEO of CEO
  social:
    - title: linkedin
      url: https://dk.linkedin.com/in/christine-redestam-70773b1

- name: Martin Nielsen
  pic: 3
  position: Danish Developer
  social:
    - title: facebook
      url: https://www.facebook.com/martindrangsfeldt.nielsen

- name: Oscar Olsson
  pic: 4
  position: Graph Developer
  social:
    - title: github
      url: https://github.com/DrunkenInfant
    - title: linkedin
      url: https://se.linkedin.com/in/oscar-olsson-57404246

- name: Tommy Ivarsson
  pic: 5
  position: Secretary Developer
  social:
    - title: github
      url: https://github.com/tomeo
    - title: linkedin
      url: https://se.linkedin.com/in/tommyi

- name: Simon Thörnqvist
  pic: 6
  position: Lead R&D
  social:
    - title: github
      url: https://github.com/drowzy
    - title: linkedin
      url: https://se.linkedin.com/in/simon-th%C3%B6rnqvist-71454461/en

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Rönnowsgatan 8DA
  - line: 252 25 Helsingborg

# Build settings
markdown: kramdown
permalink: pretty
